Fix DIGEST-MD5 auth when server address provided
When a specific server address was provided via the settings object
DIGEST-MD5 authentication would fail with:

digest_md5.py", line 345, in _make_response
    host = host.encode("idna")
AttributeError: 'NoneType' object has no attribute 'encode'

because 'service-hostname' authentication property would not be set in
such case.

Fixed by setting 'service-hostname' to the server address provided and
using the JID domain for 'service-domain' (as the transport, which
usually sets this property, won't know this in such case)